### ISSUE TITLE
Provide way to check sign of current is correct 

### ISSUE THREAD

**Issue by WardLT** [ROVI-org/battery-data-toolkit#57]
The voltage of a battery should go up as it is charged. Can we use to warn if a sign convention for current is flipped?

**Comment by victorventuri** [comment]
Yes. However, it is not as simple as look at the voltage now and in the previous step, as there can be instrument error. But some form of dV/dt analysis could be performed to warn users of our convention.

**Comment by WardLT** [comment]
A whole set of "gut checks" might be reasonable, such as verifying the sampling frequency is not way too small or large (suggesting in issue in the units for times) or inconsistencies between cycling statistics and raw data.
